config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:show, :new, :create]
  resources :services
  resources :enterprises, only: [:index, :show, :new]
  resources :candidates, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  
  validates :memo, length: { maximum: 400 }
  
  belongs_to :user
  belongs_to :enterprise
  belongs_to :service, optional: true
end

app/models/enterprise.rb
class Enterprise < ApplicationRecord
  
  def self.search(keyword)
    if keyword
      Enterprise.where(['name LIKE ?', "%#{keyword}%"])
    else
      Enterprise.all
    end
  end
  
  has_many :users
end

app/models/service.rb
class Service < ApplicationRecord
  enum kind: [:転職サイト, :転職エージェント]
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/
  validates :kind, presence: true, inclusion: { in: Service.kinds.keys }
  validates :memo, length: { maximum: 400 }
  validates :name_of_person_in_charge, allow_blank: true, length: { maximum: 50 }
  validates :tel_of_person_in_charge, allow_blank: true, format: {with: /\A\d{10}$|^\d{11}\z/ }
  validates :email_of_person_in_charge, allow_blank: true, length: { maximum: 255 },
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  
  belongs_to :user
  
  has_many :candidates
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :services
  has_many :candidates
  has_many :registerings, through: :candidates, source: :enterprise
  
  def register(enterprise)
    #binding.pry
    self.candidates.find_or_create_by(enterprise_id: enterprise.id)
  end
  
  def unregister(enterprise)
    candidate = self.candidates.find_by(enterprise_id: enterprise.id)
    candidate.destroy if candidate
  end
  
  def registering?(enterprise)
    self.registerings.include?(enterprise)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @enterprise = Enterprise.find(params[:enterprise_id])
    current_user.register(@enterprise)
    flash[:success] = '企業を候補企業として登録しました'
    redirect_to controller: :enterprises, action: :index
  end
  
  def update
    @candidate = current_user.candidates.find_by(enterprise_id: params[:enterprise_id])
    if @candidate.update(candidate_params)
      flash[:success] = '内容を保存しました'
      redirect_to enterprises_url
    else
      flash.now[:danger] = '内容が保存できませんでした'
      @enterprises = current_user.registerings.page(params[:page])
      render 'enterprises/index'
    end
  end

  def destroy
    @enterprise = Enterprise.find(params[:enterprise_id])
    current_user.unregister(@enterprise)
    flash[:danger] = '企業を候補企業から削除しました'
    redirect_to controller: :enterprises, action: :index
  end
  
  private
  
  def candidate_params
    params.require(:candidate).permit(:memo, :service_id)
  end
  
end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show]
  
  def index
    @enterprises = current_user.registerings.page(params[:page])
  end

  def show
    @enterprise = Enterprise.find(params[:id])
  end
  
  def new
    @enterprises = Enterprise.search(params[:keyword])
  end
  
  private
  
  
  def correct_user
    unless current_user.registerings.find_by(id: params[:id])
      redirect_to current_user
    end
  end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @services = current_user.services.all.page(params[:page]).per(10)
  end
  
  def show
  end
  
  def new
    @service = current_user.services.build
  end
  
  def create
    @service = current_user.services.build(service_params)
    if @service.save
      flash[:success] = '転職サービスを登録しました。'
      redirect_to @service
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    
    if @service.update(service_params)
      flash[:success] = '正常に更新されました'
      redirect_to services_url
    else
      flash.now[:danger] = '更新できませんでした。'
      render :edit
    end
  end
  
  def destroy
    @service.destroy
    flash[:success] = '削除しました。'
    redirect_back(fallback_location: current_user)
  end
  
  private
  
  def service_params
    params.require(:service).permit(:name, :url, :kind, :memo, :name_of_person_in_charge, :tel_of_person_in_charge, :email_of_person_in_charge)
  end
  
  def correct_user
    @service = current_user.services.find_by(id: params[:id])
    unless @service
      redirect_to current_user
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      redirect_to current_user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  before_action :correct_user, only: [:show]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confimation)
  end

  
  def correct_user
    #binding.pry
    unless current_user.id.to_s == params[:id]
      redirect_to current_user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, option = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/enterprises/_register_button.html.erb
<% if current_user.registering?(enterprise) %>
  <%= form_for(current_user.candidates.find_by(enterprise_id: enterprise.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :enterprise_id, enterprise.id %>
    <%= f.submit '削除', class: 'btn btn-danger candidate-regist-btn' %>
  <% end %>
<% else %>
  <%= form_for(current_user.candidates.build) do |f| %>
    <%= hidden_field_tag :enterprise_id, enterprise.id %>
    <%= f.submit '登録', class: 'btn btn-primary candidate-regist-btn' %>
  <% end %>
<% end %>

app/views/enterprises/index.html.erb
<h1>候補企業管理</h1>
<p>応募の候補としている企業をメモとあわせて管理します。</p>
<div class="text-right">
  <%= link_to '新規登録', new_enterprise_path, class: 'btn btn-primary enterprise-newregi-btn' %>
</div>

<% if @enterprises.present? %>
    <table class="enterprise-index-table table table-bordered" width="100%">
      <thead>
        <tr>
          <th width="30%">企業名</th>
          <th width="15%">掲載元/紹介元</th>
          <th width="55%">メモ</th>
        </tr>
      </thead>
      <tbody>
        <% @enterprises.each do |enterprise| %>
          <% candidate = current_user.candidates.find_by(enterprise_id: enterprise.id) %>
          <tr>
            <td>
              <%= render 'enterprises/register_button', enterprise: enterprise %>
              <%= link_to enterprise.name, enterprise_path(enterprise) %>
            </td>
            <td class="text-center">
              <% if candidate.service == nil %>
                -
              <% else %>
                <%= link_to candidate.service.name, candidate.service.url %>
              <% end %>
            </td>
            <td>
              <%= form_for(candidate) do |f| %>
                <%= f.text_field :memo, class: 'form-control' %>
                <%= hidden_field_tag :enterprise_id, enterprise.id %>
                <%= f.submit '更新', class: 'btn btn-default pull-right memo-update-btn' %>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
  <p>登録されている企業はありません。新規登録ボタンよりデータベース上の企業を登録して下さい。</p>
<% end %>

app/views/enterprises/new.html.erb
<h1>候補企業 新規登録</h1>

<%= form_tag new_enterprise_path, :method => 'get' do %>
  <p>
    企業名
    <%= text_field_tag :keyword, params[:keyword] %>
    <%= submit_tag "検索", :name => nil %>
  </p>
<% end %>

<table class="enterprise-new-table table table-bordered" width="100%">
  <thead>
    <tr>
      <th width="30%">企業名</th>
      <th width="70%">事業内容</th>
    </tr>
  </thead>
  <tbody>
    <% @enterprises.each do |enterprise| %>
      <tr>
        <td>
          <%= render 'enterprises/register_button', enterprise: enterprise %>
          <%= enterprise.name %>
        </td>
        <td><%= enterprise.business_contents %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/enterprises/show.html.erb
<h1><%= @enterprise.name %></h1>
<p><%= link_to '公式サイト', @enterprise.url %></p>

<% user_candidate = current_user.candidates.find_by(enterprise_id: @enterprise.id) %>
<%= form_for(user_candidate) do |f| %>
<table class="enterprise-show-table table table-bordered">
  <tbody>
    <tr>
      <th width="30%">代表者氏名</th>
      <td width="70%"><%= @enterprise.name_of_president %></td>
    </tr>
    <tr>
      <th>設立日</th>
      <td>
        <%= @enterprise.foundation_date.year %>/
        <%= @enterprise.foundation_date.month %>/
        <%= @enterprise.foundation_date.day %>
      </td>
    </tr>
    <tr>
      <th>所在地</th>
      <td><%= @enterprise.location %></td>
    </tr>
    <tr>
      <th>事業内容</th>
      <td><%= @enterprise.business_contents %></td>
    </tr>
    <tr>
      <th>従業員数</th>
      <td><%= number_with_delimiter(@enterprise.number_of_employees) %>名</td>
    </tr>
    <tr>
      <th>平均年齢</th>
      <td><%= @enterprise.average_age %>歳</td>
    </tr>
    <% if current_user.registering?(@enterprise) %>
      <tr>
        <th>掲載元/紹介元</th>
        <td>
          <%= f.collection_select :service_id, current_user.services, :id, :name, :prompt => "選択して下さい",class: 'form-control' %>
        </td>
      </tr>
    
      <tr>
        <th>メモ</th>
        <td>
          <%= f.text_field :memo, class: 'form-control' %>
          <%= hidden_field_tag :enterprise_id, @enterprise.id %>
          <%= f.submit '更新', class: 'btn btn-default pull-right memo-update-btn' %>
        </td>
      </tr>
      
    <% end %>
  </tbody>
</table>

            <% end %>
<div class="app-return-link"><%= link_to '候補企業管理 画面に戻る', enterprises_url %></div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-muted">
    <table width="100%">
      <tr>
        <td><div class="text-left">© Yu Kato</div></td>
        <td><div class="text-right"><a href="mailto:cpr9.yukato@gmail.com">Contact</a></div></td>
      </tr>
    </table>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default nabvar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <h1 class="logo">
          <% unless logged_in? %>
            <a class="navbar-left" href="/"><img src="/images/logo.png" alt="私の転職"></a>
          <% else %>
            <%= link_to '私の転職', user_path(current_user), class:'navbar-left logo'%>
          <% end %>
        </h1>
      </div>
      <div class="collapse navbar-collapse" id="menu">
        <ul class="nav navbar-nav navbar-right">
          <% unless logged_in? %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% else %>
            <li><%= link_to 'マイページ', user_path(current_user) %></li>
            <li><%= link_to '転職サービス管理', services_path %></li>
            <li><%= link_to '候補企業管理', enterprises_path %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewpoint" content="width=device-width, initial-scale=1"> 
    
    <title>私の転職</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <!-- app/assets/javascripts -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>

  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="form-group">
    <%= f.label :name, 'サービス名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :url, 'URL' %>
    <%= f.url_field :url, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :kind, '種別　' %>
    <%= f.select :kind, Service.kinds.keys, :prompt => "選択して下さい",class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :memo, 'メモ' %>
    <%= f.text_area :memo, :size => "1x3", class: 'form-control' %>
  </div>
  
  <hr>
  
  <div class="form-group">
    <%= f.label :name_of_person_in_charge, '担当者 名前' %>
    <%= f.text_field :name_of_person_in_charge, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :tel_of_person_in_charge, '担当者 電話番号(ハイフン無し)' %>
    <%= f.telephone_field :tel_of_person_in_charge, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email_of_person_in_charge, '担当者 メールアドレス' %>
    <%= f.email_field :email_of_person_in_charge, class: 'form-control' %>
  </div>
  
  <div class="text-right">
    <%= f.submit '登録', class: 'btn btn-success' %>
  </div>
  
<% end %>

app/views/services/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">編集ページ</div>
      <div class="panel-body">
        <%= render 'form', service: @service %>
      </div>
    </div>
  </div>
</div>
<div class="app-return-link"><%= link_to '転職サービス管理画面に戻る', services_path %></div>

app/views/services/index.html.erb
<h1>転職サービス管理</h1>
<p>利用する転職サイト、登録した転職エージェントを管理します。</p>

<div class="text-right">
  <%= link_to '新規登録', new_service_path, class: 'btn btn-primary service-newregi-btn' %>
</div>

<% if @services.present? %>
  <table class="service-index-table table table-bordered" width="100%">
    <thead>
      <tr>
        <th width="30%">サービス名</th>
        <th width="20%">種別</th>
        <th width="50%">メモ</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td>
            <%= link_to '編集', edit_service_path(service), class: 'btn btn-primary btn-md service-index-edit-btn' %>
            <%= link_to '削除', service, method: :delete, data: { confirm: "削除しますか？"}, class: 'btn btn-danger btn-md service-index-delete service-index-delete-btn' %>
            <%= link_to service.name, service.url %>
          </td>
          <% if service.kind == "転職サイト" %>
            <td><%= service.kind %></td>
          <% else %>
            <td><%= service.kind %><br>
            ＜<%= link_to '詳細', service %>＞</td>
          <% end %>
          <td>
            <%= form_for(service) do |f| %>
              <%= f.text_field :memo, class: 'form-control' %>
              <%= f.submit '更新', class: 'btn btn-default pull-right memo-btn' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>登録されているサービスはありません。新規登録ボタンより登録して下さい。</p>
<% end %>

<%= paginate @services %>

app/views/services/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">転職サービス 新規登録</div>
      <div class="panel-body">
        <%= render 'form', service: @service %>
      </div>
    </div>
  </div>
</div>
<div class="app-return-link"><%= link_to '転職サービス管理画面に戻る', services_path %></div>

app/views/services/show.html.erb
<h1><%= @service.name %></h1>

<div class="text-right">
  <%= link_to '編集', edit_service_path, class: 'btn btn-primary service-show-btn' %>
  <%= link_to '削除', @service, method: :delete, data: { confirm: "削除しますか？"}, class: 'btn btn-danger service-show-btn' %>
</div>


<table class="service-show-table table table-bordered">
  <tbody>
    <tr>
      <th width="20%">担当者名</th>
      <td width="80%"><%= @service.name_of_person_in_charge %></td>
    </tr>
    <tr>
      <th>担当者 電話番号</th>
      <td><%= @service.tel_of_person_in_charge %></td>
    </tr>
    <tr>
      <th>担当者 メールアドレス</th>
      <td><%= @service.email_of_person_in_charge %></td>
    </tr>
    <tr>
      <th>メモ</th>
      <td>
        <%= form_for(@service) do |f| %>
          <%= f.text_field :memo, class: 'form-control' %>
          <%= f.submit '更新', class: 'btn btn-default pull-right memo-update-btn' %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<div class="app-return-link"><%= link_to '転職サービス管理 画面に戻る', services_path %></div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <h1>test</h1>
<% else %>
  <div class="jumbotron">
    <div class="transparent-mask">
    <div class="container">
      <h1>私の転職</h1>
      <p>私の転職は私が管理</p>
      <div class="text-center">
        <div class="btn-group" role="group">
          <p>
            <%= link_to '新規登録', signup_path, class: 'btn btn-primary btn-lg toppage-btn' %>
            <%= link_to 'ログイン', login_path, class: 'btn btn-primary btn-lg toppage-btn' %>
          </p>
        </div>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        会員登録
      </div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          
          <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード(確認)' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <div class="text-right">
            <%= f.submit '登録', class: 'btn btn-success' %>
          </div>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-3">
    <div class="user-profile">
      <div class="icon text-center">
        <img src="<%= gravatar_url(current_user, size: 100) %>" alt="" class="img-circle"> 
      </div>
      <div class="name text-center">
        <h1><%= current_user.name %></h1>
      </div>
    </div>
  </aside>
  
  <div class="col-md-4">
    <article class="panel panel-default">
      <div class="panel panel-heading"><h3>コンタクトリスト</h3></div>
      <div class="panel-body user-show-contactlist">
        <ul>
          <% current_user.services.each do |service| %>
            <% unless service.name_of_person_in_charge.empty? %>
              <li>
                <%= service.name %><br>
                担当：<%= service.name_of_person_in_charge %> / 
                <%= link_to service.tel_of_person_in_charge, 'tel:' + service.tel_of_person_in_charge %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </article>
  </div>
  
  <div class="col-md-5">
    <article class="panel panel-default">
      <div class="panel panel-heading"><h3>候補企業</h3></div>
      <div class="panel-body user-show-candidate">
        <ul>
          <% current_user.registerings.each do |enterprise| %>
            <li>
              <%= link_to enterprise.name, enterprise_url(enterprise) %>
              (
              <% if current_user.candidates.find_by(enterprise_id: enterprise.id).service == nil %>
                -
              <% else %>
                <%= link_to current_user.candidates.find_by(enterprise_id: enterprise.id).service.name, current_user.candidates.find_by(enterprise_id: enterprise.id).service.url %>
              <% end %>
              )
            </li>
          <% end %>
        </ul>
      </div>
    </article>
  </div>
</div>